# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b23b45eaf4246d6d267b5f1bdfb3ab0f9a4647900cfa1ea71c73227abe486c7b1a244281335fc665c8eee7f0c244c8b19fb5759dc6c29249ed5a8748890dd62

test:
  secret_key_base: 4dc0224927184457adf81761f08111df8af8b35d64cbd50753579f8f03dc2d04a19bf2e1683b8229eefa9f4232da9154fd6e80b87af95b64ce8a6486d2013882

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
